// Copyright (c) 2017, Qurasense. All rights reserved.

part of app_facade;

class CountryEnum {

  static final countries = [
    new EnumWrapper('US', 'United States'),
    new EnumWrapper('DK', 'Denmark'),
    //other
    new EnumWrapper('AF', 'Afghanistan'),
    new EnumWrapper('AX', 'Åland Islands'),
    new EnumWrapper('AL', 'Albania'),
    new EnumWrapper('DZ', 'Algeria'),
    new EnumWrapper('AS', 'American Samoa'),
    new EnumWrapper('AD', 'Andorra'),
    new EnumWrapper('AO', 'Angola'),
    new EnumWrapper('AI', 'Anguilla'),
    new EnumWrapper('AQ', 'Antarctica'),
    new EnumWrapper('AG', 'Antigua and Barbuda'),
    new EnumWrapper('AR', 'Argentina'),
    new EnumWrapper('AM', 'Armenia'),
    new EnumWrapper('AW', 'Aruba'),
    new EnumWrapper('AU', 'Australia'),
    new EnumWrapper('AT', 'Austria'),
    new EnumWrapper('AZ', 'Azerbaijan'),
    new EnumWrapper('BS', 'Bahamas'),
    new EnumWrapper('BH', 'Bahrain'),
    new EnumWrapper('BD', 'Bangladesh'),
    new EnumWrapper('BB', 'Barbados'),
    new EnumWrapper('BY', 'Belarus'),
    new EnumWrapper('BE', 'Belgium'),
    new EnumWrapper('BZ', 'Belize'),
    new EnumWrapper('BJ', 'Benin'),
    new EnumWrapper('BM', 'Bermuda'),
    new EnumWrapper('BT', 'Bhutan'),
    new EnumWrapper('BO', 'Bolivia, Plurinational State of'),
    new EnumWrapper('BQ', 'Bonaire, Sint Eustatius and Saba'),
    new EnumWrapper('BA', 'Bosnia and Herzegovina'),
    new EnumWrapper('BW', 'Botswana'),
    new EnumWrapper('BV', 'Bouvet Island'),
    new EnumWrapper('BR', 'Brazil'),
    new EnumWrapper('IO', 'British Indian Ocean Territory'),
    new EnumWrapper('BN', 'Brunei Darussalam'),
    new EnumWrapper('BG', 'Bulgaria'),
    new EnumWrapper('BF', 'Burkina Faso'),
    new EnumWrapper('BI', 'Burundi'),
    new EnumWrapper('KH', 'Cambodia'),
    new EnumWrapper('CM', 'Cameroon'),
    new EnumWrapper('CA', 'Canada'),
    new EnumWrapper('CV', 'Cape Verde'),
    new EnumWrapper('KY', 'Cayman Islands'),
    new EnumWrapper('CF', 'Central African Republic'),
    new EnumWrapper('TD', 'Chad'),
    new EnumWrapper('CL', 'Chile'),
    new EnumWrapper('CN', 'China'),
    new EnumWrapper('CX', 'Christmas Island'),
    new EnumWrapper('CC', 'Cocos (Keeling) Islands'),
    new EnumWrapper('CO', 'Colombia'),
    new EnumWrapper('KM', 'Comoros'),
    new EnumWrapper('CG', 'Congo'),
    new EnumWrapper('CD', 'Congo, the Democratic Republic of the'),
    new EnumWrapper('CK', 'Cook Islands'),
    new EnumWrapper('CR', 'Costa Rica'),
    new EnumWrapper('CI', 'Côte d`Ivoire'),
    new EnumWrapper('HR', 'Croatia'),
    new EnumWrapper('CU', 'Cuba'),
    new EnumWrapper('CW', 'Curaçao'),
    new EnumWrapper('CY', 'Cyprus'),
    new EnumWrapper('CZ', 'Czech Republic'),
    new EnumWrapper('DK', 'Denmark'),
    new EnumWrapper('DJ', 'Djibouti'),
    new EnumWrapper('DM', 'Dominica'),
    new EnumWrapper('DO', 'Dominican Republic'),
    new EnumWrapper('EC', 'Ecuador'),
    new EnumWrapper('EG', 'Egypt'),
    new EnumWrapper('SV', 'El Salvador'),
    new EnumWrapper('GQ', 'Equatorial Guinea'),
    new EnumWrapper('ER', 'Eritrea'),
    new EnumWrapper('EE', 'Estonia'),
    new EnumWrapper('ET', 'Ethiopia'),
    new EnumWrapper('FK', 'Falkland Islands (Malvinas)'),
    new EnumWrapper('FO', 'Faroe Islands'),
    new EnumWrapper('FJ', 'Fiji'),
    new EnumWrapper('FI', 'Finland'),
    new EnumWrapper('FR', 'France'),
    new EnumWrapper('GF', 'French Guiana'),
    new EnumWrapper('PF', 'French Polynesia'),
    new EnumWrapper('TF', 'French Southern Territories'),
    new EnumWrapper('GA', 'Gabon'),
    new EnumWrapper('GM', 'Gambia'),
    new EnumWrapper('GE', 'Georgia'),
    new EnumWrapper('DE', 'Germany'),
    new EnumWrapper('GH', 'Ghana'),
    new EnumWrapper('GI', 'Gibraltar'),
    new EnumWrapper('GR', 'Greece'),
    new EnumWrapper('GL', 'Greenland'),
    new EnumWrapper('GD', 'Grenada'),
    new EnumWrapper('GP', 'Guadeloupe'),
    new EnumWrapper('GU', 'Guam'),
    new EnumWrapper('GT', 'Guatemala'),
    new EnumWrapper('GG', 'Guernsey'),
    new EnumWrapper('GN', 'Guinea'),
    new EnumWrapper('GW', 'Guinea-Bissau'),
    new EnumWrapper('GY', 'Guyana'),
    new EnumWrapper('HT', 'Haiti'),
    new EnumWrapper('HM', 'Heard Island and McDonald Islands'),
    new EnumWrapper('VA', 'Holy See (Vatican City State)'),
    new EnumWrapper('HN', 'Honduras'),
    new EnumWrapper('HK', 'Hong Kong'),
    new EnumWrapper('HU', 'Hungary'),
    new EnumWrapper('IS', 'Iceland'),
    new EnumWrapper('IN', 'India'),
    new EnumWrapper('ID', 'Indonesia'),
    new EnumWrapper('IR', 'Iran, Islamic Republic of'),
    new EnumWrapper('IQ', 'Iraq'),
    new EnumWrapper('IE', 'Ireland'),
    new EnumWrapper('IM', 'Isle of Man'),
    new EnumWrapper('IL', 'Israel'),
    new EnumWrapper('IT', 'Italy'),
    new EnumWrapper('JM', 'Jamaica'),
    new EnumWrapper('JP', 'Japan'),
    new EnumWrapper('JE', 'Jersey'),
    new EnumWrapper('JO', 'Jordan'),
    new EnumWrapper('KZ', 'Kazakhstan'),
    new EnumWrapper('KE', 'Kenya'),
    new EnumWrapper('KI', 'Kiribati'),
    new EnumWrapper('KP', 'Korea, Democratic People`s Republic of'),
    new EnumWrapper('KR', 'Korea, Republic of'),
    new EnumWrapper('KW', 'Kuwait'),
    new EnumWrapper('KG', 'Kyrgyzstan'),
    new EnumWrapper('LA', 'Lao People`s Democratic Republic'),
    new EnumWrapper('LV', 'Latvia'),
    new EnumWrapper('LB', 'Lebanon'),
    new EnumWrapper('LS', 'Lesotho'),
    new EnumWrapper('LR', 'Liberia'),
    new EnumWrapper('LY', 'Libya'),
    new EnumWrapper('LI', 'Liechtenstein'),
    new EnumWrapper('LT', 'Lithuania'),
    new EnumWrapper('LU', 'Luxembourg'),
    new EnumWrapper('MO', 'Macao'),
    new EnumWrapper('MK', 'Macedonia, the former Yugoslav Republic of'),
    new EnumWrapper('MG', 'Madagascar'),
    new EnumWrapper('MW', 'Malawi'),
    new EnumWrapper('MY', 'Malaysia'),
    new EnumWrapper('MV', 'Maldives'),
    new EnumWrapper('ML', 'Mali'),
    new EnumWrapper('MT', 'Malta'),
    new EnumWrapper('MH', 'Marshall Islands'),
    new EnumWrapper('MQ', 'Martinique'),
    new EnumWrapper('MR', 'Mauritania'),
    new EnumWrapper('MU', 'Mauritius'),
    new EnumWrapper('YT', 'Mayotte'),
    new EnumWrapper('MX', 'Mexico'),
    new EnumWrapper('FM', 'Micronesia, Federated States of'),
    new EnumWrapper('MD', 'Moldova, Republic of'),
    new EnumWrapper('MC', 'Monaco'),
    new EnumWrapper('MN', 'Mongolia'),
    new EnumWrapper('ME', 'Montenegro'),
    new EnumWrapper('MS', 'Montserrat'),
    new EnumWrapper('MA', 'Morocco'),
    new EnumWrapper('MZ', 'Mozambique'),
    new EnumWrapper('MM', 'Myanmar'),
    new EnumWrapper('NA', 'Namibia'),
    new EnumWrapper('NR', 'Nauru'),
    new EnumWrapper('NP', 'Nepal'),
    new EnumWrapper('NL', 'Netherlands'),
    new EnumWrapper('NC', 'New Caledonia'),
    new EnumWrapper('NZ', 'New Zealand'),
    new EnumWrapper('NI', 'Nicaragua'),
    new EnumWrapper('NE', 'Niger'),
    new EnumWrapper('NG', 'Nigeria'),
    new EnumWrapper('NU', 'Niue'),
    new EnumWrapper('NF', 'Norfolk Island'),
    new EnumWrapper('MP', 'Northern Mariana Islands'),
    new EnumWrapper('NO', 'Norway'),
    new EnumWrapper('OM', 'Oman'),
    new EnumWrapper('PK', 'Pakistan'),
    new EnumWrapper('PW', 'Palau'),
    new EnumWrapper('PS', 'Palestinian Territory, Occupied'),
    new EnumWrapper('PA', 'Panama'),
    new EnumWrapper('PG', 'Papua New Guinea'),
    new EnumWrapper('PY', 'Paraguay'),
    new EnumWrapper('PE', 'Peru'),
    new EnumWrapper('PH', 'Philippines'),
    new EnumWrapper('PN', 'Pitcairn'),
    new EnumWrapper('PL', 'Poland'),
    new EnumWrapper('PT', 'Portugal'),
    new EnumWrapper('PR', 'Puerto Rico'),
    new EnumWrapper('QA', 'Qatar'),
    new EnumWrapper('RE', 'Réunion'),
    new EnumWrapper('RO', 'Romania'),
    new EnumWrapper('RU', 'Russian Federation'),
    new EnumWrapper('RW', 'Rwanda'),
    new EnumWrapper('BL', 'Saint Barthélemy'),
    new EnumWrapper('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    new EnumWrapper('KN', 'Saint Kitts and Nevis'),
    new EnumWrapper('LC', 'Saint Lucia'),
    new EnumWrapper('MF', 'Saint Martin (French part)'),
    new EnumWrapper('PM', 'Saint Pierre and Miquelon'),
    new EnumWrapper('VC', 'Saint Vincent and the Grenadines'),
    new EnumWrapper('WS', 'Samoa'),
    new EnumWrapper('SM', 'San Marino'),
    new EnumWrapper('ST', 'Sao Tome and Principe'),
    new EnumWrapper('SA', 'Saudi Arabia'),
    new EnumWrapper('SN', 'Senegal'),
    new EnumWrapper('RS', 'Serbia'),
    new EnumWrapper('SC', 'Seychelles'),
    new EnumWrapper('SL', 'Sierra Leone'),
    new EnumWrapper('SG', 'Singapore'),
    new EnumWrapper('SX', 'Sint Maarten (Dutch part)'),
    new EnumWrapper('SK', 'Slovakia'),
    new EnumWrapper('SI', 'Slovenia'),
    new EnumWrapper('SB', 'Solomon Islands'),
    new EnumWrapper('SO', 'Somalia'),
    new EnumWrapper('ZA', 'South Africa'),
    new EnumWrapper('GS', 'South Georgia and the South Sandwich Islands'),
    new EnumWrapper('SS', 'South Sudan'),
    new EnumWrapper('ES', 'Spain'),
    new EnumWrapper('LK', 'Sri Lanka'),
    new EnumWrapper('SD', 'Sudan'),
    new EnumWrapper('SR', 'Suriname'),
    new EnumWrapper('SJ', 'Svalbard and Jan Mayen'),
    new EnumWrapper('SZ', 'Swaziland'),
    new EnumWrapper('SE', 'Sweden'),
    new EnumWrapper('CH', 'Switzerland'),
    new EnumWrapper('SY', 'Syrian Arab Republic'),
    new EnumWrapper('TW', 'Taiwan, Province of China'),
    new EnumWrapper('TJ', 'Tajikistan'),
    new EnumWrapper('TZ', 'Tanzania, United Republic of'),
    new EnumWrapper('TH', 'Thailand'),
    new EnumWrapper('TL', 'Timor-Leste'),
    new EnumWrapper('TG', 'Togo'),
    new EnumWrapper('TK', 'Tokelau'),
    new EnumWrapper('TO', 'Tonga'),
    new EnumWrapper('TT', 'Trinidad and Tobago'),
    new EnumWrapper('TN', 'Tunisia'),
    new EnumWrapper('TR', 'Turkey'),
    new EnumWrapper('TM', 'Turkmenistan'),
    new EnumWrapper('TC', 'Turks and Caicos Islands'),
    new EnumWrapper('TV', 'Tuvalu'),
    new EnumWrapper('UG', 'Uganda'),
    new EnumWrapper('UA', 'Ukraine'),
    new EnumWrapper('AE', 'United Arab Emirates'),
    new EnumWrapper('GB', 'United Kingdom'),
    new EnumWrapper('US', 'United States'),
    new EnumWrapper('UM', 'United States Minor Outlying Islands'),
    new EnumWrapper('UY', 'Uruguay'),
    new EnumWrapper('UZ', 'Uzbekistan'),
    new EnumWrapper('VU', 'Vanuatu'),
    new EnumWrapper('VE', 'Venezuela, Bolivarian Republic of'),
    new EnumWrapper('VN', 'Viet Nam'),
    new EnumWrapper('VG', 'Virgin Islands, British'),
    new EnumWrapper('VI', 'Virgin Islands, U.S.'),
    new EnumWrapper('WF', 'Wallis and Futuna'),
    new EnumWrapper('EH', 'Western Sahara'),
    new EnumWrapper('YE', 'Yemen'),
    new EnumWrapper('ZM', 'Zambia'),
    new EnumWrapper('ZW', 'Zimbabwe'),
  ];

  static EnumWrapper find(String s) {
    return countries.firstWhere((ew)=>ew.name == s, orElse: null);
  }

}