server:
  port: 8080
#  compression:
#    enabled: true
#    min-response-size: 2048
#    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
management:
  security:
    enabled: false
version:
  hash: replace_buildhash
  buildtime: replace_buildtime
