name: app_facade
version: 1.0.0
description: Facade to the cloud API and generated models
dependencies:
  http: ^0.11.0
  intl: ^0.15.2
  meta: ^1.1.1
  uuid: ^0.5.3

dev_dependencies:
  test: ^0.12.0

transformers:
