apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.67.218
  ports:
  - port: 80
    name: gateway
    targetPort: 8080
    nodePort: 32754
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: user
  labels:
    app: user
spec:
#  type: NodePort
  ports:
  - port: 8082
    name: user
    targetPort: 8082
#    nodePort: 32756
  selector:
    app: user
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: health
  labels:
    app: health
spec:
#  type: NodePort
  ports:
  - port: 8081
    name: health
    targetPort: 8081
#    nodePort: 32755
  selector:
    app: health
