name: app_web
description: Qurasense web app
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  http: "^0.11.3+16"
  app_facade:
      path: ../facade

dev_dependencies:
  angular_test: ^1.0.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  sass_builder: ^1.1.5

transformers:
- sass_builder
- angular:
    entry_points:
      - public/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    sourceMaps: true
- dart_to_js_script_rewriter
